---
title: "MP4"
author: "Christine Chu"
date: "April 25, 2018"
output: html_document
--- 

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
install.packages("mdsr")
install.packages("RMySQL")
library(mdsr)
library(RMySQL)
library(scales)
```

Database for Querying 
#replace quotation with dataset we choose
```{r}
db <- dbConnect_scidb(dbname = "lahman")
```


# Individual chunks to prevent overwriting of code.
Christine 
```{r}
series <- dbConnect_scidb(dbname = "lahman") 
series_df <- series %>% 
  dbGetQuery("SELECT DISTINCT ls.yearID, tf.franchName as 'Team_name', lt.teamID, sp.teamIDwinner as 'WinnerID',sp.round, sp.wins
FROM lahman.Salaries ls 
#JOIN lahman.HallOfFame hf ON hf.playerID = ls.playerID
JOIN lahman.Teams lt ON lt.teamID = ls.teamID
JOIN lahman.TeamsFranchises tf ON tf.franchID = lt.franchID
#join the series post data frame with the year ID to see the winner. 
JOIN lahman.SeriesPost sp ON ls.yearID = sp.yearID
WHERE lt.teamID = sp.teamIDwinner
#WHERE team = SeriesPost.team 
AND ls.yearID = 2015
;")

series_df
```

```{r}
win_rate <- dbConnect_scidb(dbname = "lahman") 
win_ratedf <- win_rate %>% 
  dbGetQuery("SELECT DISTINCT lt.yearID, tf.franchName, W/G as Win_rate
FROM lahman.Teams lt
JOIN lahman.Salaries ls ON lt.teamID = ls.teamID
JOIN lahman.TeamsFranchises tf ON tf.franchID = lt.franchID
WHERE lt.yearID = 2015
#GROUP BY tf.franchID
;")

wr_df <- win_ratedf %>% 
  select(yearID, franchName, Win_rate )

wr_plot <- ggplot(wr_df, aes(franchName, Win_rate)) + geom_bar(stat = "identity", fill = "Green")

wr_plot +
   scale_x_discrete() +
  scale_y_continuous(expand = c(0, 0), labels = percent, breaks = c(0,0.2, 0.4, 0.6, 0.8, 1), limit = c(0,1)) +
  ggtitle("Winning rate by Franchise") + 
  theme(axis.text.x = element_text(angle = 45, hjust = 1)) +
  labs(x = "Franchise Name", y = "Winning Rate in 2015")


```




Nybria 
```{r}
db <- dbConnect_scidb(dbname = "imdb")
db %>%
  dbGetQuery("SELECT * FROM kind_type;")

# we cannot access this data base
cb <- dbConnect_scidb(dbname = "citibike")
# we cannot access this data base
ntaxi <- dbConnect_scidb(dbname = "nyctaxi")

```

```{r}
#I am trying to combine two tables the Hall of Fame and Salary, I am trying things out, so I have been having trouble 

dbGetQuery("SELECT hf.playerID, hf.inducted, s.playerID, s.salary
FROM lahman.HallOfFame hf
JOIN lahman.Salaries s ON hf.playerID = s.playerID
ORDER BY s.salary desc;")


# combining tables 

dbGetQuery("SELECT s.teamID, s.playerID, lt.teamID, lt.franchID, tf.franchID, tf.franchName, hf.playerID, hf.inducted
FROM lahman.Salaries
JOIN lahman.Teams lt ON s.teamID = lt.teamID
JOIN lahman.TeamsFranchises tf ON  lt.franchID = tf.franchID
JOIN lahman.HallOfFame hf ON s.playerID = hf.playerID
WHERE hf.inducted = 'Y'
AND s.yearID >= 2016;")

```

```{r}
bball <- dbConnect_scidb(dbname = "lahman")

bball_df <- bball %>%
  dbGetQuery("SELECT DISTINCT s.teamID, s.playerID, lt.teamID, lt.franchID, tf.franchID, tf.franchName, hf.playerID, hf.inducted, s.salary, s.yearid
FROM lahman.Salaries s
JOIN lahman.Teams lt ON s.teamID = lt.teamID
JOIN lahman.TeamsFranchises tf ON  lt.franchID = tf.franchID
JOIN lahman.HallOfFame hf ON s.playerID = hf.playerID
WHERE hf.inducted = 'N'
GROUP BY hf.playerID;
")

rod_salary <- bball %>%
  dbGetQuery("SELECT DISTINCT s.teamID, s.playerID, lt.teamID, lt.franchID, tf.franchID, tf.franchName, s.salary, s.yearid
FROM lahman.Salaries s
JOIN lahman.Teams lt ON s.teamID = lt.teamID
JOIN lahman.TeamsFranchises tf ON  lt.franchID = tf.franchID
WHERE s.playerID = 'rodrial01'
;
")

rod_line <-ggplot(data = rod_salary, aes(y = salary, x = yearid, color = franchName )) + geom_point()

rod_line 

```



Julia
```{r}
db <- dbConnect_scidb(dbname = "lahman")

cow <- db %>% 
  dbGetQuery("SELECT DISTINCT ls.yearID, lt.Rank, lt.franchID, ls.playerID, ls.salary, tf.franchName
FROM lahman.Salaries ls 
JOIN lahman.Teams lt ON lt.teamID = ls.teamID
JOIN TeamsFranchises tf ON lt.franchID = tf.franchID
WHERE lt.yearID > 2010
GROUP BY playerID
ORDER BY Salary desc

;")

cow2 <- cow %>%
  select(Rank, franchName, salary, yearID)


cow3 <- cow2 %>%
  group_by(franchName) %>%
  mutate(avgsal = mean(salary))



library(ggthemes)
cowplot <- ggplot(cow3, aes(x=franchName, y=avgsal, col=Rank)) +
  geom_point() 

cowplot +
  geom_point(shape = 21) +
  scale_x_discrete() +
  scale_y_continuous() +
  ggtitle("Average Salary by Franchise") + 
  theme(axis.text.x = element_text(angle = 90, hjust = 1)) +
  labs(x = "Franchise Name", y = "Average Salary 2013-2018")
```

--------------------------------------------------------
This project would not have been possible without github [^1].

##Links: 
[^1]: [Link to our GitHub Repositoury](https://github.com/christine-chu/MP4)